<a href="https://colab.research.google.com/github/zdg12/fizzbuzz/blob/main/03_exercise3cdi1212_ipynb_json.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorchの基本機能に関する演習問題
特に指示がない限り，問題の回答に当たってはPyTorchの機能を利用すること

### 問題1:
NumPy配列 `np.array([1, 2, 3, 4, 5])` をPyTorchテンソルに変換するプログラムを作成してください．
ただし，データ型は32bit floatとなるようにしてください．
また，生成したPyTorchテンソルの`dtype`, `shape`, `device` を表示してください．

In [2]:
# こちらにコードを記述してください。

import numpy as np
import torch

np_array = np.array([1, 2, 3, 4, 5])

tensor = torch.tensor(np_array, dtype=torch.float32)

print(f'dtype: {tensor.dtype}')
print(f'shape: {tensor.shape}')
print(f'device: {tensor.device}')

dtype: torch.float32
shape: torch.Size([5])
device: cpu


### 問題2:
要素が`[-6, -3, 0, 3, 6, 9]`である1階テンソル（ベクトル）を生成し，その要素を表示するプログラムを作成してください．

In [4]:
# こちらにコードを記述してください。
import torch

tensor = torch.tensor([-6, -3, 0, 3, 6, 9])

print(tensor)

tensor([-6, -3,  0,  3,  6,  9])


### 問題3:
$$\begin{pmatrix}
0 & 1 & 2 & 3 \\
4 & 5 & 6 & 7 \\
8 & 9 & 10 & 11 \\
12 & 13 & 14 & 15 \\
16 & 17 & 18 & 19 \\
\end{pmatrix}$$
という，形（サイズ）が`[5, 4]`の2階テンソル（行列）を作成し，以下ぞれぞれの要素を取得するプログラムを作成してください．
- 2行3列の要素（最も左上の要素は1行1列とする．以下同様）
- 第2列の要素すべて
- 奇数番目の行の要素すべて

In [6]:
# こちらにコードを記述してください。
import torch
tensor = torch.arange(1, 21).reshape(5, 4)
tensor23 = tensor[1,2]
tensor2 = tensor[:,1]
tensor1 = tensor[::2,:]
print(tensor23)
print(tensor2)
print(tensor1)

tensor(7)
tensor([ 2,  6, 10, 14, 18])
tensor([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20]])


### 問題4:
$A=\begin{pmatrix} 2 & -1 \\ 1 & 1 \end{pmatrix}, x=\begin{pmatrix} 1 \\ 1 \end{pmatrix}, b=\begin{pmatrix} 1 \\ 2 \end{pmatrix}$のとき，$Ax-b$を計算するプログラムを作成してください．

In [7]:
# こちらにコードを記述してください。
import torch

A = torch.tensor([[2, -1], [1, 1]])
x = torch.tensor([1, 1])
b = torch.tensor([1, 2])

result = torch.matmul(A, x) - b

print(result)

tensor([0, 0])


### 問題5:
関数$f(x)=x^3-12x+10$について，$x=-2, 0, 2$における導関数の値を計算するプログラムを作成してください．

In [20]:
# こちらにコードを記述してください。
import torch

def f(x):
    return x**3 - 12*x + 10

x = torch.tensor([-2.0, 0.0, 2.0], requires_grad=True)

y = f(x)

y.backward(torch.ones_like(x))
a = x.grad.int()
print(a)

tensor([  0, -12,   0], dtype=torch.int32)
